# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
use_sim_time: true

moveit_simple_controller_manager:
  controller_names:
    - scara_controller
    - gripper_controller

  scara_controller:
    type: FollowJointTrajectory
    joints:
      - scara_q1_link_joint
      - scara_q2_link_joint
      - scara_gripper_arm_link_joint
      - fingers_base_link_joint
    action_ns: follow_joint_trajectory
    default: true
    use_sim_time: true
  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - finger_1_link_joint
      - finger_2_link_joint
    action_ns: follow_joint_trajectory
    default: true
    use_sim_time: true